In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[8,8,4],[7,9,5],[5,12,7]],columns=["cgpa","profile_score","lpa"])

In [ ]:
df


,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,5,12,7


In [ ]:
def initialize_Parameters(layers_dim):
  np.random.seed(3)
  parameters={}
  L=len(layers_dim)
  for l in range(1,L):
    parameters['W'+str(l)]=np.ones((layers_dim[l-1],layers_dim[l]))*0.1
    parameters['b'+str(l)]=np.zeros((layers_dim[l],1))
  return parameters

In [ ]:
def Linear_forward(A_prev,W,b):
  z=np.dot(W.T,A_prev)+b
  return z

In [ ]:
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)//2
  for l in range(1,L+1):
    A_prev=A
    W1=parameters["W"+str(l)]
    b1=parameters["b"+str(l)]
    # print("A"+str(l-1),A_prev)
    # print("W"+str(l),W1)
    # print("b"+str(l),b1)
    # print("--"*20)
    A=Linear_forward(A_prev,W1,b1)
    # print("A"+str(l)+":",A)
    # print("**"*30)
  return A,A_prev

In [ ]:
X=df[["cgpa","profile_score"]].values[0].reshape(2,1)
Y=df[["lpa"]].values[0][0]

parameters=initialize_Parameters([2,2,1])
y_hat,A1=L_layer_forward(X,parameters)
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
y_hat=y_hat[0][0]

In [ ]:
def update_params(parameters,y,y_hat,A1,X):
  parameters["W2"][0][0]=parameters["W2"][0][0]+(0.001*2*(y-y_hat)*A1[0][0])
  parameters["W2"][1][0]=parameters["W2"][1][0]+(0.001*2*(y-y_hat)*A1[1][0])
  parameters["W2"][0][0]=parameters["W2"][0][0]+(0.001*2*(y-y_hat))

  parameters["W1"][0][0]=parameters["W1"][0][0]+(0.001*2*(y-y_hat)*parameters["W2"][0][0]*X[0][0])
  parameters["W1"][1][0]=parameters["W1"][0][1]+(0.001*2*(y-y_hat)*parameters["W2"][1][0]*X[1][0])
  parameters["b1"][0][0]=parameters["b1"][0][0]+(0.001*2*(y-y_hat)*parameters["W2"][0][0])

  parameters['W1'][1][0]=parameters['W1'][1][0]+(0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1]=parameters['W1'][1][1]+(0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0]+(0.001*2*(y-y_hat)*parameters['W2'][1][0])
  return parameters

In [ ]:
update_params(parameters,Y.item(),y_hat.item(),A1,X)

{'W1': array([[0.10701473, 0.1       ],
        [0.11316274, 0.10658137]]),
 'b1': array([[0.00087684],
        [0.00082267]]),
 'W2': array([[0.119136],
        [0.111776]]),
 'b2': array([[0.]])}

In [ ]:
parameters

{'W1': array([[0.10701473, 0.1       ],
        [0.11316274, 0.10658137]]),
 'b1': array([[0.00087684],
        [0.00082267]]),
 'W2': array([[0.119136],
        [0.111776]]),
 'b2': array([[0.]])}

In [ ]:
# epochs implementation
params=initialize_Parameters([2,2,1])
epochs=50
for i in range(epochs):
  loss=[]
  for j in range(df.shape[0]):
    x=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]
    y_hat,A1=L_layer_forward(x,params)
    y_hat=y_hat[0]

    update_params(params,y.item(),y_hat.item(),A1,x)
    loss.append((y-y_hat)**2)
  print('Epoch - ',i+1,'Loss-',np.array(loss).mean())
parameters

Epoch -  1 Loss- 25.52043070719837
Epoch -  2 Loss- 21.81073454789735
Epoch -  3 Loss- 17.133553646935837
Epoch -  4 Loss- 11.999521955482109
Epoch -  5 Loss- 7.433905799826429
Epoch -  6 Loss- 4.247130473877939
Epoch -  7 Loss- 2.4974582007821
Epoch -  8 Loss- 1.719905902853184
Epoch -  9 Loss- 1.4284584612257376
Epoch -  10 Loss- 1.3301506832521048
Epoch -  11 Loss- 1.2939444661173907
Epoch -  12 Loss- 1.2723166135254682
Epoch -  13 Loss- 1.2513040714459245
Epoch -  14 Loss- 1.2282036915328893
Epoch -  15 Loss- 1.2033740642032182
Epoch -  16 Loss- 1.177658914333672
Epoch -  17 Loss- 1.1517381795052781
Epoch -  18 Loss- 1.1260518571359122
Epoch -  19 Loss- 1.1008565226112348
Epoch -  20 Loss- 1.0762902725366192
Epoch -  21 Loss- 1.0524200593721762
Epoch -  22 Loss- 1.0292717494888919
Epoch -  23 Loss- 1.0068480800363513
Epoch -  24 Loss- 0.9851390575430014
Epoch -  25 Loss- 0.964127877752671
Epoch -  26 Loss- 0.9437942629219095
Epoch -  27 Loss- 0.9241163321014888
Epoch -  28 Loss- 0.

{'W1': array([[0.10701473, 0.1       ],
        [0.11316274, 0.10658137]]),
 'b1': array([[0.00087684],
        [0.00082267]]),
 'W2': array([[0.119136],
        [0.111776]]),
 'b2': array([[0.]])}

# Keras code


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=df=pd.DataFrame([[8,8,4],[7,9,5],[5,12,7]],columns=["cgpa","profile_score","lpa"])

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.get_weights()

[array([[-0.09225595, -0.45904136],
        [ 1.0502053 , -0.39260828]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0217768],
        [-1.3384875]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),np.array([0.,0.],dtype=np.float32),np.array([[0.1],[0.1]],dtype=np.float32),np.array([0.],dtype=np.float32)]

In [ ]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 26.5271
Epoch 2/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.2770
Epoch 3/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.0761
Epoch 4/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.8306
Epoch 5/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.5924
Epoch 6/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.3146
Epoch 7/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.0629
Epoch 8/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.8345
Epoch 9/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 24.5657
Epoch 10/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.2610
Epoch 11/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.9948
Epoch 12/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.7372
Epoch 13/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.4313
Epoch 14/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 23.1361
Epoch 15/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22.8230
Epoch 16/75
3/3 ━━━

In [ ]:
model.get_weights()

[array([[0.33172253, 0.33172253],
        [0.31577578, 0.31577578]], dtype=float32),
 array([0.22625469, 0.22625469], dtype=float32),
 array([[0.32598463],
        [0.32598463]], dtype=float32),
 array([0.17723551], dtype=float32)]